spring.application.name=kintai
server.port=8081
# データベースを自動で作成して接続する設定
spring.datasource.url=jdbc:h2:mem:kintaidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# アプリ起動時に、この後作るSQLファイルを自動実行する設定
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update